---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: chip
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: chip-gateway
  namespace: chip
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "chip.k8s.raj.ninja"
    - "chip.chip.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chip-gateway
  namespace: chip
spec:
  hosts:
  - "chip.chip.svc.cluster.local"
  - "chip.k8s.raj.ninja"
  gateways:
  - chip-gateway
  http:
  - route:
    - destination:
        host: chip-active
        port:
          number: 8080
    retries:
      attempts: 0
      perTryTimeout: 500ms
      retryOn: refused-stream
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: chip-gateway-preview
  namespace: chip
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "chip-preview.k8s.raj.ninja"
    - "chip-preview.chip.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chip-gateway-preview
  namespace: chip
spec:
  hosts:
  - "chip-preview.chip.svc.cluster.local"
  - "chip-preview.k8s.raj.ninja"
  gateways:
  - chip-gateway-preview
  http:
  - route:
    - destination:
        host: chip-preview
        port:
          number: 8080
    retries:
      attempts: 0
      perTryTimeout: 500ms
      retryOn: refused-stream
---
apiVersion: v1
kind: Service
metadata:
  name: chip-active
  namespace: chip
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"    
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip 
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chip-preview
  namespace: chip
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"    
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip 
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: chip-http-check
  namespace: chip
spec:
  metrics:
  - name: http-bench-analysis
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:
                istio-injection: disabled
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - name: http-bench-analysis
                image: rogerw/cassowary:v0.14.0
                command: ["cassowary"]
                args: ["run", "-u", "http://chip-preview.chip.svc.cluster.local:8080/healthcheck", "-c", "3", "-n", "1000"]
              restartPolicy: Never
    count: 1
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: chip-prometheus-http-status-query
  namespace: chip
spec:
  metrics:
  - name: http-bench-analysis
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:
                istio-injection: disabled
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - name: http-bench-analysis
                image: rogerw/cassowary:v0.14.0
                command: ["cassowary"]
                args: ["run", "-u", "http://chip-preview.chip.svc.cluster.local:8080/healthcheck", "-c", "3", "-n", "10000"]
              restartPolicy: Never
    count: 1
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: chip-error-rate-check
  namespace: chip
spec:
  metrics:
  - name: success-rate
    interval: 2m
    successCondition: result[0] >= 0.95
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090
        query: |
          sum(irate(
            istio_requests_total{destination_service=~"chip-preview.chip.svc.cluster.local",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{destination_service=~"chip-preview.chip.svc.cluster.local"}[5m]
          ))
    count: 1          
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: chip
  namespace: chip
spec:
  replicas: 10
  strategy:
    blueGreen: 
      activeService: chip-active
      previewService: chip-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: chip-http-warm-up
        - templateName: chip-error-rate-check
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      annotations:
        istio-injection: enabled
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"           
      labels:
        app: chip
        name: chip
        version: v1
    spec:
      containers:
      - name: chip
        image: fidelissauro/chip:v2
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"  
        - name: CHAOS_MONKEY_MODE
          value: "hell" 
        - name: CHAOS_MONKEY_LATENCY
          value: "true"            
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"   
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"   
        - name: CHAOS_MONKEY_MEMORY
          value: "true"
        - name: VERSION
          value: "v4"
      terminationGracePeriodSeconds: 60