{
 "title": "Argo-Rollouts - Artigo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Preview Version - Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=\"chip-preview.chip.svc.cluster.local\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Active Version - Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=\"chip-active.chip.svc.cluster.local\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Preview Version - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"chip-preview.chip.svc.cluster.local\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Active Version - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"chip-active.chip.svc.cluster.local\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}